### ISSUE TITLE
Phone number form updates

### ISSUE THREAD

**Issue by asmolentzov** [le3ah/thirsty_plants#129]
- When entering phone number, text is white so doesn't show up
- Would be nice to have a flash message so the user knows their number has been saved
- Testing in local host doesn't seem to work - phone number form doesn't disappear from dashboard

**Comment by Mackenzie-Frey** [comment]
The white text is probably from inheritance of a css form class.

**Comment by bendelonlee** [comment]
You can fix the css by giving the form it's own class or id.
