### ISSUE TITLE
Create Garden

### ISSUE THREAD

**Issue by le3ah** [le3ah/thirsty_plants#3]
From my dashboard, when I select 'create garden', I am redirected to the create_garden_path.  I can fill in a garden name, zip code, and multiple plants.  Each plant has a name and watering requirements. 
After I select 'create my garden' I am redirected to that garden's show page where I see the appropriate details.

**Comment by Mackenzie-Frey** [comment]
branch name: create_garden
Completed dashboard link and form for new garden.
Does not currently include plant creation.
(Mackenzie and Anna)

**Comment by Mackenzie-Frey** [comment]
User Story complete -
Sad Path testing desired:
User does not include plants - should still be able to create garden.
User cannot input incorrect data types into form.
Visually test error messages are appearing via running the server.
(Mackenzie and Anna)

**Comment by asmolentzov** [comment]
User does not include plants - should still be able to create garden - tested and fixed. 
(Anna)
