### ISSUE TITLE
Add Plant to Garden

### ISSUE THREAD

**Issue by le3ah** [le3ah/thirsty_plants#7]
From my garden's show page, I can click a link to add a plant to my garden.  When I click this link, I am redirected to a create plant page.  On this page, I can add a plant name and times per week.  After I select 'create plant', I am redirected to my garden show page and I see a flash message that says, "Party in my plants, you've created a new plant!"

**Comment by asmolentzov** [comment]
User story complete.
Pending discussion with team regarding edge case/sad path testing.
