### ISSUE TITLE
Generate Schedule

### ISSUE THREAD

**Issue by le3ah** [le3ah/thirsty_plants#8]
On my dashboard, I see a link to generate my watering schedule.  When I click this button, I am redirected to the schedule index page.  The index page shows the schedules for each of my gardens.

The schedule index page should show the schedule for each of my gardens. The schedule includes then watering schedule for each plant.

(reference wireframes)

**Comment by Mackenzie-Frey** [comment]
Completed the button from the dashboard to View a Watering Schedule. 

Ben and I agreed that for MVP it is okay for the View a Watering Schedule button to appear if the user has a garden, but has no plants. 

Ben is grabbing the rest of the card which is -The index page shows the schedules for each of my gardens.-
